Renaming ESortOrder to EBCSortOrder to fix a name conflict within Unreal Engine
Error highlight from build job:
/Users/buildmaster/jenkins-slave/workspace/bitHeads_BrainCloud_Client_BuildTest_UnrealEngine_MacOS/artifacts/BCClient_5.6/HostProject/Plugins/BCClient/Source/BCClientPlugin/Public/BrainCloudLeaderboard.h(26): Error: Enum 'ESortOrder' shares engine name 'ESortOrder' with enum 'ESortOrder' in /Users/Shared/Epic Games/UE_5.6/Engine/Plugins/VirtualProduction/VirtualCamera/Source/VirtualCamera/Public/FunctionLibraries/AssetFilteringAndSortingFunctionLibrary.h(15)