Release/5.9 (#152)
* Redid the widget in UE5.0 version and fixed compile errors for UE5.0 (#145)

* Redid the widget in UE5.0 version and fixed compile errors for UE5.0

* Update to widget made in UE 5.0

* Update client lib version to 5.8.1

* UpdateCodes

* Update Copyrights in source SDK Clients to 2026 across all file headers - Unreal

* Renaming ESortOrder to EBCSortOrder to fix a name conflict within Unreal Engine

Error highlight from build job:
/Users/buildmaster/jenkins-slave/workspace/bitHeads_BrainCloud_Client_BuildTest_UnrealEngine_MacOS/artifacts/BCClient_5.6/HostProject/Plugins/BCClient/Source/BCClientPlugin/Public/BrainCloudLeaderboard.h(26): Error: Enum 'ESortOrder' shares engine name 'ESortOrder' with enum 'ESortOrder' in /Users/Shared/Epic Games/UE_5.6/Engine/Plugins/VirtualProduction/VirtualCamera/Source/VirtualCamera/Public/FunctionLibraries/AssetFilteringAndSortingFunctionLibrary.h(15)

* Implemented new UserItems APIs (#150)

* Implemented new APIs: AwardUserItemsWithOptions, GetItemsOnPromotion, GetItemPromotionDetails and PurchaseUserItemsWithOptions

* Add new blueprint functions for the new APIs

* Tweaking GetItemsOnPromotion API to include optionsJson as an option

Test result from tweak:
LogBrainCloudComms: Sending request:{"packetId":1,"sessionId":"qktkvbgu121lj8qieng43saa4o","gameId":"20001","messages":[{"service":"userItems","operation":"GET_ITEMS_ON_PROMOTION","data":{"shopId":"","includeDef":true,"includePromotionDetails":true,"optionsJson":{"category":"equipment"}}}]}
LogBrainCloudComms: Got response: {"packetId":1,"responses":[{"data":{"items":[],"promotionDetails":[]},"status":200}],"events":[]}

---------

Co-authored-by: franco <82105876+francobithead@users.noreply.github.com>

* Updated to 5.9

* Update Reason Codes, and copyright

---------

Co-authored-by: Franco Lago <82105876+francobithead@users.noreply.github.com>
Co-authored-by: nick-bithead <79153661+nick-bithead@users.noreply.github.com>